# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7495cd7388a497de4a9af3bc646d8fbed4c53e4fbae9722eb5ca6b7777115e56521f97e0570237a22907ee6eb5287422af7159db6a11a829c3e22dbbed166cb

test:
  secret_key_base: a355f394db9bac9ac010beae8c79df0df3fd4d1f20cc5a172e4c44ae913ce0beca9c4f7ff7f3cb939717d2215140312ed18a155cb57feae0f067e561097d4682

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
